--This code was generated by OpenAI's ChatGPT. (Model: GPT 3.5 Turbo)
print("Downloading UI...")
writefile("VRCUI.rbxm", game:HttpGet("https://github.com/bakersrule2020/vrchat-ui-lib/raw/main/VRCUI.rbxm"))
-- Assuming you have a function getcustomasset that returns the AssetId string
local assetId = getcustomasset(readfile("VRCUI.rbxm"))

-- Load objects from the .rbxm file
local AssetService = game:GetService("AssetService")
local success, objects = pcall(function()
    return AssetService:GetObjects(assetId)
end)
local objtoreturn = nil
if success then
    -- Assuming the VRCUI object is in the first index of the objects table
    local vrcui = objects[1]

    -- Parent the VRCUI to CoreGui
    vrcui.Parent = game:GetService("CoreGui")
    objtoreturn = vrcui
else
    warn("Failed to load objects: " .. objects)
end
if not objtoreturn == nil then
    return objtoreturn
else
    error("Failed to get the UI object!")
end
