--This code was generated by OpenAI's ChatGPT. (Model: GPT 3.5 Turbo)

-- Assuming you have a function getcustomasset that returns the AssetId string
local assetId = getcustomasset(game:HttpGet("https://github.com/bakersrule2020/vrchat-ui-lib/raw/main/VRCUI.rbxm"))

-- Load objects from the .rbxm file
local AssetService = game:GetService("AssetService")
local success, objects = pcall(function()
    return AssetService:GetObjects(assetId)
end)

if success then
    -- Assuming the VRCUI object is in the first index of the objects table
    local vrcui = objects[1]

    -- Parent the VRCUI to CoreGui
    vrcui.Parent = game:GetService("CoreGui")
else
    warn("Failed to load objects: " .. objects)
end
